[package]
name = "wallpaper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
windows = { version = "0.58", features = ["Win32_UI_WindowsAndMessaging"] }
home = "0.5"

[profile.dev]
debug = 0

[profile.release]
debug = 0
strip = true
